// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Kp3kFw7qdo9xBWPmeialOLvsoM6BRXY',
    appId: '1:887087858534:web:a9b10148c6d303e48abea7',
    messagingSenderId: '887087858534',
    projectId: 'smart-city-aa45d',
    authDomain: 'smart-city-aa45d.firebaseapp.com',
    databaseURL: 'https://smart-city-aa45d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-city-aa45d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWpIUSXbU6MVsPS00wUKhHKJ6VtmNDDKY',
    appId: '1:887087858534:android:26f3b60ac9b064188abea7',
    messagingSenderId: '887087858534',
    projectId: 'smart-city-aa45d',
    databaseURL: 'https://smart-city-aa45d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-city-aa45d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA64pmNi-iAqKtOjt8wzGdFUTANYHN8h5c',
    appId: '1:887087858534:ios:f5c557b2e6bb878a8abea7',
    messagingSenderId: '887087858534',
    projectId: 'smart-city-aa45d',
    databaseURL: 'https://smart-city-aa45d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-city-aa45d.appspot.com',
    iosBundleId: 'com.example.apkTes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA64pmNi-iAqKtOjt8wzGdFUTANYHN8h5c',
    appId: '1:887087858534:ios:f5c557b2e6bb878a8abea7',
    messagingSenderId: '887087858534',
    projectId: 'smart-city-aa45d',
    databaseURL: 'https://smart-city-aa45d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-city-aa45d.appspot.com',
    iosBundleId: 'com.example.apkTes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2Kp3kFw7qdo9xBWPmeialOLvsoM6BRXY',
    appId: '1:887087858534:web:54d84e1def457f0f8abea7',
    messagingSenderId: '887087858534',
    projectId: 'smart-city-aa45d',
    authDomain: 'smart-city-aa45d.firebaseapp.com',
    databaseURL: 'https://smart-city-aa45d-default-rtdb.firebaseio.com',
    storageBucket: 'smart-city-aa45d.appspot.com',
  );
}
